module "gke" {
  source     = "terraform-google-modules/kubernetes-engine/google//modules/safer-cluster"
  version    = "3.0.0"
  project_id = var.project_id
  regional   = var.regional
  zones                           = local.zones
  name                            = local.cluster_name
  region                          = var.region
  network                         = module.vpc.network_name
  subnetwork                      = module.vpc.subnets_names["${local.private_subnet_index}"]
  ip_range_pods                   = var.pods_range_name
  ip_range_services               = var.svc_range_name
  enable_private_endpoint         = var.enable_private_endpoint
  grant_registry_access           = var.grant_registry_access
  add_cluster_firewall_rules      = var.add_cluster_firewall_rules
  firewall_inbound_ports          = var.cluster_firewall_inbound_ports
  kubernetes_version              = var.kubernetes_version
  master_ipv4_cidr_block          = var.cluster_ip_range
  enable_vertical_pod_autoscaling = var.enable_vertical_pod_autoscaling
  cluster_resource_labels         = local.cluster_labels
  horizontal_pod_autoscaling      = var.horizontal_pod_autoscaling
  compute_engine_service_account  = var.compute_engine_service_account
  default_max_pods_per_node       = var.max_pods_per_node
  node_pools_labels               = var.nodepool_labels
  node_pools_taints               = var.nodepool_taints
  master_authorized_networks      = var.master_authorized_networks
  node_pools = var.nodepools
}